export default [
  { id: 1, 
    user: 'user 1', 
    comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi luctus justo vel consequat faucibus. Vivamus et ipsum maximus est ultrices cursus in sed velit. Sed velit metus, fermentum at lacinia sed, sagittis posuere risus. Nullam leo tortor, imperdiet vel ullamcorper varius, consectetur at libero. Duis urna nisi, aliquet dignissim turpis in, dignissim tincidunt mi. Donec eget tempus nisl. Fusce lobortis, lorem eget tempus porttitor, elit libero bibendum erat, eu volutpat turpis elit at est. Nullam condimentum ultrices libero ac auctor. Nulla in neque nisi. Morbi non dapibus quam. Aliquam pharetra at risus nec congue. Nullam et sapien libero. Nulla eget ante consectetur, fermentum turpis vitae, vestibulum leo. Nunc eu sapien vel augue luctus euismod. Phasellus quis vulputate orci. Nam rhoncus, nunc et aliquam interdum, elit dui pulvinar augue, a pulvinar tellus diam eget leo.', 
    dateCreate: new Date(2018, 1, 14),
    refComment: null, },
  { id: 2, 
    user: 'user 2', 
    dateCreate: new Date(2018, 2, 22),
    comment: 'The quick brown fox jumps over the lazy dog', 
    refComment: null },
  { id: 3, 
    user: 'user 3', 
    dateCreate: new Date(2018, 2, 18),
    comment: 'The quick brown fox jumps over the lazy dog', 
    refComment: 1 },
  { id: 4, 
    user: 'user 4', 
    dateCreate: new Date(2018, 2, 22),
    comment: 'The quick brown fox jumps over the lazy dog', 
    refComment: 1 }, 
  { id: 5, 
    user: 'user 2', 
    dateCreate: new Date(2018, 5, 8),
    comment: 'The quick brown fox jumps over the lazy dog', 
    refComment: 1 },
  { id: 6, 
    user: 'user 2', 
    dateCreate: new Date(2018, 5, 18),
    comment: 'The quick brown fox jumps over the lazy dog', 
    refComment: 2 },
  { id: 7, 
    user: 'user 4', 
    dateCreate: new Date(2018, 6, 18),
    comment: 'The quick brown fox jumps over the lazy dog', 
    refComment: 2 },
  { id: 8, 
    user: 'user 1', 
    dateCreate: new Date(2018, 6, 18),
    comment: 'The quick brown fox jumps over the lazy dog', 
    refComment: 3 },
  { id: 9, 
    user: 'user 2', 
    dateCreate: new Date(2018, 7, 18),
    comment: 'The quick brown fox jumps over the lazy dog', 
    refComment: 3 },
  { id: 10, 
    user: 'user 2', 
    dateCreate: new Date(2018, 12, 18),
    comment: 'The quick brown fox jumps over the lazy dog', 
    refComment: 6 },
  { id: 11, 
    user: 'user 4', 
    dateCreate: new Date(2018, 3, 10),
    comment: 'The quick brown fox jumps over the lazy dog', 
    refComment: null },
  { id: 12, 
    user: 'user 3', 
    dateCreate: new Date(2018, 3, 1),
    comment: 'The quick brown fox jumps over the lazy dog', 
    refComment: null },
]